#!/usr/bin/env bash
#
# Put `explorer` on PATH and the skills where each agent harness looks for them.
#
# The skills are installed once into ~/.agents/skills and symlinked from each
# harness, so every harness reads the same files and none of them can drift.
# Everything points back at this checkout, so `git pull` updates all of them.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
BIN_DIR="${BIN_DIR:-$HOME/.local/bin}"
SHARED_SKILLS="${SHARED_SKILLS:-$HOME/.agents/skills}"

say() { printf '  %s\n' "$1"; }

refuse() {
  printf 'installer refused: %s; resolve manually and retry\n' "$1" >&2
  exit 1
}

exact_error() {
  printf '%s\n' "$1" >&2
  exit 1
}

command -v node >/dev/null || { echo "node is required (22 or newer)" >&2; exit 1; }

node_major="$(node -p 'process.versions.node.split(".")[0]')"
if [ "$node_major" -lt 22 ]; then
  echo "node $node_major is too old; 22 or newer is required for --experimental-strip-types" >&2
  exit 1
fi

# The singular spelling is intentionally not parsed by the shell. A path with
# spaces is one literal value; HARNESS_DIRS retains its old whitespace-list
# contract for compatibility.
if [ "${HARNESS_DIR+x}" = x ] && [ -n "${HARNESS_DIRS:-}" ]; then
  exact_error 'set only one of HARNESS_DIR or HARNESS_DIRS'
fi

# Resolve a path lexically before looking at the filesystem. node is already a
# required prerequisite and path.resolve removes `..` without following links.
absolute_path() {
  node -e 'process.stdout.write(require("node:path").resolve(process.argv[1]))' -- "$1"
}

# Existing configured roots are canonicalized once. Missing suffixes are kept
# below the nearest existing canonical directory and are only created after all
# preflight checks pass.
canonical_root() {
  local input="$1"
  local absolute current part canonical
  local -a missing=()

  absolute="$(absolute_path "$input")" || refuse "could not resolve configured root '$input'"
  current="$absolute"
  while [ ! -e "$current" ] && [ ! -L "$current" ]; do
    part="${current##*/}"
    [ -n "$part" ] || break
    missing=("$part" "${missing[@]}")
    current="${current%/*}"
    [ -n "$current" ] || current=/
  done

  if [ -L "$current" ] || [ -e "$current" ]; then
    [ -d "$current" ] || refuse "configured root is not a directory: $input"
    [ "${#missing[@]}" -eq 0 ] || [ ! -L "$current" ] \
      || refuse "configured root has a symlinked ancestor: $input"
    canonical="$(cd -- "$current" && pwd -P)" || refuse "could not inspect configured root '$input'"
  else
    refuse "configured root has no existing directory ancestor: $input"
  fi

  for part in "${missing[@]}"; do
    canonical="$canonical/$part"
  done
  printf '%s\n' "$canonical"
}

# A destination role is allowed to be absent or already managed. Everything
# else is a legacy/drift case requiring manual resolution. Symlinks are checked
# before -e so dangling links cannot look absent.
wrapper_matches() {
  local path="$1"
  cmp -s "$path" <(
    printf '%s\n' \
      '#!/usr/bin/env sh' \
      '# Generated by scripts/install.sh. Runs from source so it is never stale.' \
      "exec node --experimental-strip-types \"$ROOT/src/cli.ts\" \"\$@\""
  )
}

check_wrapper_destination() {
  local path="$1"
  if [ -L "$path" ]; then
    refuse "foreign wrapper destination: $path"
  elif [ -e "$path" ]; then
    [ -f "$path" ] && wrapper_matches "$path" || refuse "foreign wrapper destination: $path"
  fi
}

check_skill_destination() {
  local path="$1" expected="$2" resolved
  if [ -L "$path" ]; then
    resolved="$(cd -- "$path" 2>/dev/null && pwd -P)" || refuse "foreign skill destination: $path"
    [ "$resolved" = "$expected" ] || refuse "foreign skill destination: $path"
  elif [ -e "$path" ]; then
    refuse "foreign skill destination: $path"
  fi
}

check_harness_destination() {
  local path="$1" expected="$2" target resolved
  if [ -L "$path" ]; then
    target="$(readlink "$path")" || refuse "foreign harness destination: $path"
    resolved="$(node -e 'process.stdout.write(require("node:path").resolve(process.argv[1], process.argv[2]))' -- "$(dirname "$path")" "$target")" \
      || refuse "foreign harness destination: $path"
    [ "$resolved" = "$expected" ] || refuse "foreign harness destination: $path"
  elif [ -e "$path" ]; then
    refuse "foreign harness destination: $path"
  fi
}

# Keep role paths disjoint. This catches both exact collisions and a role
# accidentally nested inside another role's destination.
path_contains() {
  local parent="$1" child="$2"
  if [ "$parent" = / ]; then
    [[ "$child" = /* ]]
  else
    [ "$child" = "$parent" ] || [[ "$child" = "$parent"/* ]]
  fi
}

role_paths=()
role_names=()
add_role() {
  local name="$1" path="$2"
  local i
  for i in "${!role_paths[@]}"; do
    if path_contains "${role_paths[$i]}" "$path" || path_contains "$path" "${role_paths[$i]}"; then
      refuse "destination roles overlap: ${role_names[$i]} and $name"
    fi
  done
  role_names+=("$name")
  role_paths+=("$path")
}

# Sources are part of the contract and must be real directories before links
# are considered managed.
SOURCE_EXPLORER="$(cd -- "$ROOT/skills/explorer" 2>/dev/null && pwd -P)" \
  || refuse "source skill directory is missing: $ROOT/skills/explorer"
SOURCE_NAVIGATOR="$(cd -- "$ROOT/skills/navigator" 2>/dev/null && pwd -P)" \
  || refuse "source skill directory is missing: $ROOT/skills/navigator"

BIN_ROOT="$(canonical_root "$BIN_DIR")"
SHARED_ROOT="$(canonical_root "$SHARED_SKILLS")"
BIN_DEST="$BIN_ROOT/explorer"
SHARED_EXPLORER="$SHARED_ROOT/explorer"
SHARED_NAVIGATOR="$SHARED_ROOT/navigator"

# Harness selection is the only compatibility parsing in this installer.
# Defaults and a singular missing directory are skipped; explicit legacy list
# entries must already exist so a typo cannot silently change the install set.
harness_inputs=()
harness_roots=()
harness_skipped=()
if [ "${HARNESS_DIR+x}" = x ]; then
  [ -n "$HARNESS_DIR" ] || refuse 'HARNESS_DIR must be one literal directory path'
  if [ -d "$HARNESS_DIR" ]; then
    harness_inputs+=("$HARNESS_DIR")
  elif [ -e "$HARNESS_DIR" ] || [ -L "$HARNESS_DIR" ]; then
    refuse "configured harness root is not a directory: $HARNESS_DIR"
  else
    harness_skipped+=("$HARNESS_DIR")
  fi
elif [ -n "${HARNESS_DIRS:-}" ]; then
  read -r -a legacy_harnesses <<< "$HARNESS_DIRS"
  for dir in "${legacy_harnesses[@]}"; do
    [ -d "$dir" ] || exact_error 'invalid HARNESS_DIRS entry; use HARNESS_DIR for a literal path'
    harness_inputs+=("$dir")
  done
else
  harness_inputs=(
    "$HOME/.claude/skills"
    "$HOME/.config/polytoken/skills"
  )
  for dir in "${harness_inputs[@]}"; do
    if [ ! -d "$dir" ]; then
      harness_skipped+=("$dir")
    fi
  done
fi

# Canonicalize active harness roots once and retain only existing directories.
# The default/singular skip entries were already removed from this list.
for dir in "${harness_inputs[@]}"; do
  if [ -d "$dir" ]; then
    harness_roots+=("$(canonical_root "$dir")")
  fi
done

add_role 'wrapper' "$BIN_DEST"
add_role 'shared explorer' "$SHARED_EXPLORER"
add_role 'shared navigator' "$SHARED_NAVIGATOR"
for root in "${harness_roots[@]}"; do
  add_role "harness explorer ($root)" "$root/explorer"
  add_role "harness navigator ($root)" "$root/navigator"
done

# Validate every destination before mkdir, rm, ln, or write. The root paths are
# canonical, so each destination must remain directly below its authorized root.
path_below_root() {
  local root="$1" path="$2"
  path_contains "$root" "$path" || refuse "destination escapes canonical root: $path"
}
path_below_root "$BIN_ROOT" "$BIN_DEST"
path_below_root "$SHARED_ROOT" "$SHARED_EXPLORER"
path_below_root "$SHARED_ROOT" "$SHARED_NAVIGATOR"
for root in "${harness_roots[@]}"; do
  path_below_root "$root" "$root/explorer"
  path_below_root "$root" "$root/navigator"
done

check_wrapper_destination "$BIN_DEST"
check_skill_destination "$SHARED_EXPLORER" "$SOURCE_EXPLORER"
check_skill_destination "$SHARED_NAVIGATOR" "$SOURCE_NAVIGATOR"
for root in "${harness_roots[@]}"; do
  check_harness_destination "$root/explorer" "$SHARED_EXPLORER"
  check_harness_destination "$root/navigator" "$SHARED_NAVIGATOR"
done

# Everything above is still read-only. Show the canonical destinations before
# creating either root, then create only the two roots owned by this installer.
echo "explorer: installing from $ROOT"
say "resolved binary   $BIN_DEST"
say "resolved skill    $SHARED_EXPLORER"
say "resolved skill    $SHARED_NAVIGATOR"
for root in "${harness_roots[@]}"; do
  say "resolved harness  $root/explorer"
  say "resolved harness  $root/navigator"
done
for dir in "${harness_skipped[@]}"; do
  say "skipped  $dir (not present)"
done

mkdir -p "$BIN_ROOT" "$SHARED_ROOT"

# Revalidate immediately before changing any destination. This is deliberately
# not advertised as a concurrent/adversarial-mutation guarantee.
check_wrapper_destination "$BIN_DEST"
check_skill_destination "$SHARED_EXPLORER" "$SOURCE_EXPLORER"
check_skill_destination "$SHARED_NAVIGATOR" "$SOURCE_NAVIGATOR"
for root in "${harness_roots[@]}"; do
  check_harness_destination "$root/explorer" "$SHARED_EXPLORER"
  check_harness_destination "$root/navigator" "$SHARED_NAVIGATOR"
done

# A wrapper runs the TypeScript source rather than a symlink to dist/. A built
# bundle goes stale the moment src/ changes and still runs, which is exactly the
# class of failure this tool exists to catch. Source costs about six
# milliseconds more per invocation and cannot be wrong.
if [ ! -e "$BIN_DEST" ] && [ ! -L "$BIN_DEST" ]; then
  cat > "$BIN_DEST" <<WRAPPER
#!/usr/bin/env sh
# Generated by scripts/install.sh. Runs from source so it is never stale.
exec node --experimental-strip-types "$ROOT/src/cli.ts" "\$@"
WRAPPER
  chmod +x "$BIN_DEST"
fi
say "binary   $BIN_DEST"

if [ ! -e "$SHARED_EXPLORER" ] && [ ! -L "$SHARED_EXPLORER" ]; then
  ln -s "$SOURCE_EXPLORER" "$SHARED_EXPLORER"
fi
say "skill    $SHARED_EXPLORER"
if [ ! -e "$SHARED_NAVIGATOR" ] && [ ! -L "$SHARED_NAVIGATOR" ]; then
  ln -s "$SOURCE_NAVIGATOR" "$SHARED_NAVIGATOR"
fi
say "skill    $SHARED_NAVIGATOR"

for root in "${harness_roots[@]}"; do
  if [ ! -e "$root/explorer" ] && [ ! -L "$root/explorer" ]; then
    ln -s "$SHARED_EXPLORER" "$root/explorer"
  fi
  say "harness  $root/explorer"
  if [ ! -e "$root/navigator" ] && [ ! -L "$root/navigator" ]; then
    ln -s "$SHARED_NAVIGATOR" "$root/navigator"
  fi
  say "harness  $root/navigator"
done

echo
if ! printf '%s' ":$PATH:" | grep -q ":$BIN_ROOT:"; then
  echo "  note: $BIN_ROOT is not on your PATH. Add it, or move the wrapper." >&2
fi

"$BIN_DEST" --version
echo "  run 'explorer --help' to see the commands."
