#!/usr/bin/env bash
#
# Put `explorer` on PATH and the skill where each agent harness looks for it.
#
# The skill is installed once into ~/.agents/skills and symlinked from each
# harness, so every harness reads the same file and none of them can drift.
# Everything points back at this checkout, so `git pull` updates all of them.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BIN_DIR="${BIN_DIR:-$HOME/.local/bin}"
SHARED_SKILLS="${SHARED_SKILLS:-$HOME/.agents/skills}"

# Harnesses that read a skills directory. A harness that is not installed is
# skipped rather than created: an empty skills directory in a tool you do not
# use is confusing, not helpful. Override to add one, or to install somewhere
# harmless while testing this script.
if [ -n "${HARNESS_DIRS:-}" ]; then
  read -r -a HARNESS_DIRS <<< "$HARNESS_DIRS"
else
  HARNESS_DIRS=(
    "$HOME/.claude/skills"
    "$HOME/.config/polytoken/skills"
  )
fi

say() { printf '  %s\n' "$1"; }

command -v node >/dev/null || { echo "node is required (22 or newer)" >&2; exit 1; }

node_major="$(node -p 'process.versions.node.split(".")[0]')"
if [ "$node_major" -lt 22 ]; then
  echo "node $node_major is too old; 22 or newer is required for --experimental-strip-types" >&2
  exit 1
fi

echo "explorer: installing from $ROOT"

# A wrapper that runs the TypeScript source rather than a symlink to dist/.
# A built bundle goes stale the moment src/ changes and still runs, which is
# exactly the class of failure this tool exists to catch. Source costs about six
# milliseconds more per invocation and cannot be wrong.
mkdir -p "$BIN_DIR"
# Remove first. A redirect follows a symlink and writes to whatever it points at,
# so re-installing over an older symlinked install overwrites that target instead
# of replacing the link — and fails outright once the target is gone.
rm -f "$BIN_DIR/explorer"
cat > "$BIN_DIR/explorer" <<WRAPPER
#!/usr/bin/env sh
# Generated by scripts/install.sh. Runs from source so it is never stale.
exec node --experimental-strip-types "$ROOT/src/cli.ts" "\$@"
WRAPPER
chmod +x "$BIN_DIR/explorer"
say "binary   $BIN_DIR/explorer"

mkdir -p "$SHARED_SKILLS"
ln -sfn "$ROOT/skills/explorer" "$SHARED_SKILLS/explorer"
say "skill    $SHARED_SKILLS/explorer"

for dir in "${HARNESS_DIRS[@]}"; do
  if [ -d "$dir" ]; then
    ln -sfn "$SHARED_SKILLS/explorer" "$dir/explorer"
    say "harness  $dir/explorer"
  else
    say "skipped  $dir (not present)"
  fi
done

echo
if ! printf '%s' ":$PATH:" | grep -q ":$BIN_DIR:"; then
  echo "  note: $BIN_DIR is not on your PATH. Add it, or move the wrapper." >&2
fi

"$BIN_DIR/explorer" --version
echo "  run 'explorer --help' to see the commands."
